### model
model_name_or_path: /nvmedata/jonathanl/models/Llama-3.2-11B-Vision-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /nvmedata/jonathanl/LLaMA-Factory/examples/deepspeed/jonathan.json

### dataset
dataset: makcedward_hudocvqa_11_06_2024
template: llama3_vl
cutoff_len: 4096
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: /nvmedata/jonathanl/models/llama3.2_11b_instruct_sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000