### model
model_name_or_path: /import/ml-sc-scratch3/shubhangiu/llama_3.2_checkpoints/saves/llama-3.2-11b_llava_med_pretraining/full/sft/checkpoint-3651

### method
stage: sft
do_train: true
finetuning_type: lora
deepspeed: /import/ml-sc-scratch4/shubhangiu/etash_fork/LLaMA-Factory/examples/deepspeed/ds_z3_offload_config.json
lora_target: ['k_proj', 'v_proj', 'q_proj', 'o_proj', 'multi_modal_projector']

### dataset
dataset: llava-med-train  
template: llama3_vl
cutoff_len: 1024
overwrite_cache: true
preprocessing_num_workers: 4

### output
output_dir: /import/ml-sc-scratch3/shubhangiu/llama_3.2_checkpoints/saves/llama-3.2-11b_llava_med_pretraining/full/sft/finetuning_with_checkpoint_3651_with_lora_with_mm_projector 
logging_steps: 1
save_steps: 396
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2 
gradient_accumulation_steps: 16
learning_rate: 1.0e-6
num_train_epochs: 3
lr_scheduler_type: cosine
warmup_ratio: 0.03
weight_decay: 0.0
bf16: true
ddp_timeout: 180000000
save_total_limit: 10


### eval
eval_dataset: llava-med-val
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 396 

### report 
report_to: wandb
run_name: test_run
