### model
model_name_or_path: /import/ml-sc-nlpcheckpoints-scratch3/jonathanl/generic_checkpoints/llama3.2/Llama-3.2-11B-Vision-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /import/ml-sc-scratch5/etashg/llama3.2/LLaMA-Factory/examples/deepspeed/jonathan.json

### dataset
dataset: nidhi
template: llava
cutoff_len: 512
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: saves/qwen2_vl-7b/full/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 128
learning_rate: 1.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
