### model
model_name_or_path: /import/ml-sc-nlpcheckpoints-scratch3/jonathanl/generic_checkpoints/llama3.2/Llama-3.2-11B-Vision-Instruct

### method
stage: sft
do_train: true
finetuning_type: full
deepspeed: /import/ml-sc-scratch1/jonathanl/repositories/EtashGuha-LLaMA-Factory/examples/deepspeed/jonathan.json

### dataset
dataset: hungarian_pretrain_train_11_14_2024
eval_dataset: hungarian_pretrain_val_11_14_2024
template: llama3_vl
cutoff_len: 2048
overwrite_cache: true
preprocessing_num_workers: 16


### output
output_dir: /import/ml-sc-nlpcheckpoints-scratch2/jonathanl/finetuning_results/llama3.2_finetuning/pretrain_hungarian_11_15_24_idc
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### wandb
report_to: wandb
run_name: lr1e-5_gbs64_ss2048_11_15_24

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 4
learning_rate: 1.0e-5
num_train_epochs: 1
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000